import dash_html_components as html
import dash_core_components as dcc

from imasyndata_web.plotly_config import BG_COLOR_PLOT


def cheatsheet():
    return [html.Tr([html.Td(),
                     html.Td("Query key", style={"text-align": "center", "paddingTop": "5px", "paddingBottom": "0px"}),
                     html.Td("Query property", style={"text-align": "center", "paddingTop": "5px", "paddingBottom": "0px"}),
                     html.Td("Match", style={"text-align": "center", "paddingTop": "5px", "paddingBottom": "0px"}),
                     html.Td("Example", style={"text-align": "center", "paddingTop": "5px", "paddingBottom": "0px"}),
                     html.Td()],
                    style={"font-weight": "650",
                           "backgroundColor": "#94ba4a",
                           }),
            html.Tr([html.Td(),
                     html.Td([html.Div("basic")]),
                     html.Td([html.Div(".doi")]),
                     html.Td([html.Div("- recipes by DOI")]),
                     html.Td([html.Div("$basic.doi: {10.1039/C5TC01731A}")]),
                     html.Td()],style={"background-color": BG_COLOR_PLOT}),
            html.Tr([html.Td(),
                     html.Td([html.Div("material/target/precursors")]),
                     html.Td([html.Div(".formula"),
                              html.Div(".allElem"),
                              html.Div(".anyElem"),
                              html.Div(".exactElem"),
                              html.Div(".ion"),
                              html.Div(".oxidation"),
                              html.Div(".mpid"),
                              html.Div(".Hf/Hd")
                              ]),
                     html.Td([html.Div("- material formula"),
                              html.Div("- all given elements"),
                              html.Div("- any given element"),
                              html.Div("- exact composition"),
                              html.Div("- ion given in formula"),
                              html.Div("- elements oxidation state"),
                              html.Div("- Materials Project IDs"),
                              html.Div("- formation/decomposition enthalpies")
                              ]),
                     html.Td([html.Div("$target.formula: {Li(Mn2-xCox)O4}"),
                              html.Div("$target.allElem: {Li, Co, Mn}"),
                              html.Div("$target.anyElem: {Au, Pt}"),
                              html.Div("$target.exactElem: {Na, V, F}"),
                              html.Div("$precursors.ion: {NH4}"),
                              html.Div("$target.oxidation: {Mg: 2.0, H: -1.0}"),
                              html.Div("$material.mpid: {mp-1008653, mp-27461}"),
                              html.Div("$material.Hf: {>0.5}")
                              ]),
                     html.Td()], style={"background-color": BG_COLOR_PLOT}),
            html.Tr([html.Td(),
                     html.Td([html.Div("reaction")]),
                     html.Td([html.Div(".reactant"),
                              html.Div(".product"),
                              html.Div(".compound")]),
                     html.Td([html.Div("- materials from reaction left side"),
                              html.Div("- materials from reaction right side"),
                              html.Div("- materials in reaction (any side)")]),
                     html.Td([html.Div("$reaction.reactant: {Si, Nb}"),
                              html.Div("$reaction.product: {Mg2Sn}"),
                              html.Div("$reaction.compound: {LiMnO4}")]),
                     html.Td()], style={"background-color": BG_COLOR_PLOT}),
            html.Tr([html.Td(),
                     html.Td([html.Div("synthesis")]),
                     html.Td([html.Div(".temperature"),
                              html.Div(".time")]),
                     html.Td([html.Div("- heating temperature"),
                              html.Div("- heating time")]),
                     html.Td([html.Div("$synthesis.temperature: {>1100}"),
                              html.Div("$synthesis.time: {=20}")
                              ]),
                     html.Td()], style={"background-color": BG_COLOR_PLOT})
            ]
